"""Compatibility facade for cattorch's domain-specific production kernels."""

from cattorch.util.instruction.optimized_convolution import (
    OptimizedConvolutionInstruction,
    OptimizedPoolingInstruction,
)
from cattorch.util.instruction.optimized_elementwise import (
    FastElementwiseInstruction,
    FusedArithmeticInstruction,
    OptimizedElementwiseInstruction,
    OptimizedSwiGLUInstruction,
    PairedLinearSwiGLUInstruction,
)
from cattorch.util.instruction.optimized_linear import (
    CachedCausalScoreInstruction,
    CachedSoftmaxInstruction,
    CachedSoftmaxValueInstruction,
    CachedValueMatMulInstruction,
    CausalScoreInstruction,
    CausalSoftmaxInstruction,
    CausalValueMatMulInstruction,
    FastCachedSoftmaxInstruction,
    FastCausalSoftmaxInstruction,
    FastLowRankMatMulInstruction,
    FastPrunedMatMulInstruction,
    LinearInstruction,
    OptimizedMatMulInstruction,
    QKVLinearInstruction,
)
from cattorch.util.instruction.optimized_normalization import (
    FastLayerNormInstruction,
    FastSoftmaxInstruction,
    OptimizedBatchNormInstruction,
    OptimizedLayerNormInstruction,
    OptimizedMeanInstruction,
    OptimizedRMSNormInstruction,
    OptimizedSoftmaxInstruction,
)
from cattorch.util.instruction.optimized_tensor import (
    CachedPositionEmbeddingAddInstruction,
    CachedPositionEmbeddingInstruction,
    EmbeddingAddInstruction,
    OptimizedCatInstruction,
    OptimizedEmbeddingInstruction,
    OptimizedGetItemInstruction,
    OptimizedMaskedFillInstruction,
    OptimizedTransposeInstruction,
)

__all__ = [
    "CachedCausalScoreInstruction",
    "CachedPositionEmbeddingAddInstruction",
    "CachedPositionEmbeddingInstruction",
    "CachedSoftmaxInstruction",
    "CachedSoftmaxValueInstruction",
    "CachedValueMatMulInstruction",
    "CausalScoreInstruction",
    "CausalSoftmaxInstruction",
    "CausalValueMatMulInstruction",
    "EmbeddingAddInstruction",
    "FastCachedSoftmaxInstruction",
    "FastCausalSoftmaxInstruction",
    "FastElementwiseInstruction",
    "FastLayerNormInstruction",
    "FastLowRankMatMulInstruction",
    "FastPrunedMatMulInstruction",
    "FastSoftmaxInstruction",
    "FusedArithmeticInstruction",
    "LinearInstruction",
    "OptimizedBatchNormInstruction",
    "OptimizedCatInstruction",
    "OptimizedConvolutionInstruction",
    "OptimizedElementwiseInstruction",
    "OptimizedEmbeddingInstruction",
    "OptimizedGetItemInstruction",
    "OptimizedLayerNormInstruction",
    "OptimizedMaskedFillInstruction",
    "OptimizedMatMulInstruction",
    "OptimizedMeanInstruction",
    "OptimizedPoolingInstruction",
    "OptimizedRMSNormInstruction",
    "OptimizedSoftmaxInstruction",
    "OptimizedSwiGLUInstruction",
    "PairedLinearSwiGLUInstruction",
    "OptimizedTransposeInstruction",
    "QKVLinearInstruction",
]
